apiVersion: v1
data:
  index.html: "<html>\r\n  <body>\r\n    <h1>Dev Server : Hello Buddy, served by Kustomize!</h1>\r\n
    \ </body>\r\n</html>"
kind: ConfigMap
metadata:
  name: indexfile-8bd7tt5k4h
---
apiVersion: v1
data:
  index.html: "<html>\r\n  <body>\r\n    <h1>Hello Buddy, served by Kustomize!</h1>\r\n
    \ </body>\r\n</html>"
kind: ConfigMap
metadata:
  name: nginx-config-cbm67m9gcc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app
  name: nginx-svc
spec:
  ports:
  - port: 9090
    targetPort: 80
  - port: 80
    targetPort: 80
  selector:
    app: nginx-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-app
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - image: nginx:1.25
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-config
      volumes:
      - configMap:
          name: nginx-config-cbm67m9gcc
        name: nginx-config
