apiVersion: v1
kind: Pod
metadata:
    name: kubia-manual-v1
    labels:
      app: kubia-pod
spec:
    containers:
    - name: kubia
      image: luksa/kubia
      ports:
      - containerPort: 8080
        protocol: TCP
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"