apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-deployment
  annotations:         # for extra info / hints
    owner: "team-frontend"
    purpose: "demo-annotations"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia-pod
  template:
    metadata:
      labels:
        app: kubia-pod
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - containerPort: 8080
        env:
        - name: WELCOME_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: kubia-config-map # name that we give in metadata of ConfigMap
              key: WELCOME_MESSAGE