apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-sidecar
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}   # temporary storage shared by both containers

  containers:
  - name: nginx
    image: nginx:1.25
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx

  - name: log-shipper
    image: busybox
    command: ["sh", "-c", "tail -n+1 -F /logs/access.log"]
    volumeMounts:
    - name: shared-logs
      mountPath: /logs
